pipeline {
	agent any

	parameters { choice(name: 'batch', choices: ['cp-b08', 'cp-b09', 'cp-b11'], description: '') }
	stages {
		stage('number1') {
			steps {
				echo "this is $batch batch"
				sh 'ls -l'
			}
		}
		stage('number2') {
			steps {
				sh 'df -kh'
				sh 'pwd'
			}
		}
		stage('num3-git') {
			steps {
				git url: 'https://github.com/cloudPatashala/jenkins.git'
			}
		}
		stage('num4') {
			steps {
				sh 'ls -l'
			}
		}
			
	}
}